name: youtube_downloader
description: A YouTube video downloader using Flutter
publish_to: "none" # Remove this line if you want to publish to the app store


version: 1.0.0+1

environment:
  sdk: ^3.6.1


dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  flutter_downloader: ^1.12.0
  url_launcher: ^6.3.1
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  video_player: ^2.5.1
  device_info_plus: ^11.3.0
  file_picker: ^8.3.3
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
